version: "3.9"  # optional since v1.27.0

services:
 db: 
  container_name: postgres-migration
  image: postgres:14.5-alpine
  restart: always
  environment: 
    - POSTGRES_USER=${TYPEORM_USERNAME}
    - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    - POSTGRES_DB=${TYPEORM_DATABASE}
  volumes:
    - ./pgdata:/var/lib/postgresql/data
  ports:
    - ${TYPEORM_PORT}:${TYPEORM_PORT}